A few minor fixes for absolute calibration factor estimation (#1324)
* Fix CR CSV parser for single corner reflector case

* Fix timestamp in abscal output JSON

The timestamp was an isce3.core.DateTime object which caused a TypeError
to be raised in python=3.11.0 when the data was encoded in JSON format:

```
TypeError: Object of type DateTime is not JSON serializable
```

The issue is resolved by converting the DateTime object to an ISO 8601
string prior to JSON encoding.

* Fix corner reflector ID parsing

Fix an issue where the corner reflector ID string was sometimes parsed
as an empty string by interpreting it as `np.object_` rather than
`np.str_`.

* Use a custom JSON encoder for DateTimes

... instead of manually converting the timestamp to a string

* Treat CR CSV header row as a comment

... rather than unconditionally skipping the first row. This makes the
CSV parser more robust to input files that may be missing a header row,
but otherwise mimic the format of the UAVSAR corner reflector data.

* Use super() to access base class methods

* Use more explicit conversion to ISO 8601 string

* Ignore header row if fields are surrounded by quotes as well