Fix type annotations for Python<3.9 (#1512)
The return type annotation for `PolChannelSet.frequencies()` causes an
error in Python 3.9

```
TypeError: 'type' object is not subscriptable
```

The syntax for `list[str]` was added in Python 3.9. In order to use it
in Python 3.8, we need to add the following import line:

```
from __future__ import annotations
```