Fix regressions in isce-3#1184 for Python 3.8 (#1308)
Abstract classes in `collections.abc` don't support type
parameterization in Python<3.9, resulting in errors like:

```
TypeError: 'ABCMeta' object is not subscriptable
```

The problem is resolved by simply adding `from __future__ import
annotations` (requires Python 3.7+).