Disable docker prune in profiler job
We're seeing errors such as
```
+ docker cp isce-build-jenkins-pr-pipeline-test-XXXX:/isce-bld/Test.xml .ci/images/conda
Error: No such container:path: isce-build-jenkins-pr-pipeline-test-XXXX:/isce-bld/Test.xml
```

Perhaps this is caused by images being pruned before they are finished
running? This appears to be the only PR-run prune command, so let's
disable this and see if it fixes it.